DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='Home'),
    path('career/',views.career,name='Career'),
    path('about/',views.about,name='About'),
    path('contact/',views.contact,name='Contact'),
    path('firstapp/',include('firstapp.urls')),
    
    
    path("__reload__/",include("django_browser_reload.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoProject/firstapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # localhost:8000/firstapp/
    path('',views.firstapp,name='firstapp'),
    path('order/',views.order,name="order"),
    path('detail/<int:script_id>/', views.detail, name='detail'),
    path('script-stores/', views.script_store_view, name='script_stores')
] 

DjangoProject/firstapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class scriptingLang(models.Model):
    LANG_TYPE_CHOICE = [
        ('Js', 'JavaScript'),
        ('JSX', 'Javascript_Extension'),
        ('Rb', 'Ruby'),
        ('JAVA', 'Java'),
        ('Py', 'Python'),
    ]
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='firstapp/')
    date_added = models.DateTimeField(default=timezone.now)
    type = models.CharField(max_length=4, choices=LANG_TYPE_CHOICE)
    description = models.TextField(default='')
    def __str__(self):
        return self.name
    
# One to Many relationship:
# review is associated with scripting language
class ScriptLangReview(models.Model):
    script = models.ForeignKey(scriptingLang, on_delete=models.CASCADE,related_name ='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    comment =models.TextField()
    date_added =models.DateTimeField(default = timezone.now)    
    
    def __str__(self):
        return f'{self.user.username} review for {self.script.name}'


# many to many

class ScriptsStore(models.Model):
    name = models.CharField( max_length=50)
    location= models.CharField( max_length=50)
    script_varieties = models.ManyToManyField(scriptingLang, related_name='ScriptsStore')
    
    def __str__(self):
        return  self.name

# one to one
class scriptCertificates(models.Model):
    script = models.OneToOneField(scriptingLang, related_name='certificate', on_delete=models.CASCADE)
    certificate_number = models.CharField(max_length=50)
    issue_date = models.DateTimeField(default=timezone.now)
    valid_until= models.DateTimeField()
    
    
    def __str__(self):
        return f'Certificate for {self.script.name}'
    
    # do migration
    # python  manage.py makemigrations
    # python manage.py migrate
    # python mange.py runserver 
    # goto admin.py
    # import above class from .models
    # class chai

DjangoProject/firstapp/forms.py
from django import forms
from .models import scriptingLang

class ScriptVarietyForm(forms.Form):
    script_variety = forms.ModelChoiceField(queryset=scriptingLang.objects.all(),label="Select script variety")

DjangoProject/DjangoProject/views.py
from django.http import HttpResponse
from django.shortcuts import render
def home(request):
    # return HttpResponse("Hello, This is my first Django Project, you are at Home page. ")
    return render(request, 'website/index.html')

def about(request):
    # return HttpResponse("Hello, This is my first Django Project, you are at About page. ")
    return render(request,'website/about.html')

def contact(request):
    # return HttpResponse("Hello, This is my first Django Project, you are at Contact page. ")
    return render(request,'website/contact.html')

def career(request):
    return render(request,'website/career.html')

DjangoProject/firstapp/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from .models import scriptingLang, ScriptsStore
from .forms import ScriptVarietyForm 
# Create your views here.

def firstapp(request):
    scripting_langs = scriptingLang.objects.all()
    return render(request, 'firstapp/firstapp.html', {'scriptingLang': scripting_langs})


def detail(request, script_id):
    get_obj = get_object_or_404(scriptingLang, pk=script_id)
    return render(request, 'firstapp/detail.html', {'get_obj': get_obj})


def order(request):
    return render(request, 'firstapp/order.html')

def script_store_view(request):
    stores =None
    if request.method =="POST":
        form = ScriptVarietyForm(request.POST)
        if  form.is_valid():
            script_variety = form.cleaned_data['script_variety'] # from.py link
            stores =ScriptsStore.objects.filter(script_varieties=script_variety)
    else:
        form = ScriptVarietyForm()
    return render(request, 'firstapp/script_stores.html',{'stores':stores,'form':form})

DjangoProject/firstapp/templates/firstapp/detail.html
{% extends 'layout.html' %}

{% block title %}
    Detail Page for {{ get_obj.name }}
{% endblock %}

{% block content %}
    <h1>{{ get_obj.name }}</h1>
    <div class="scriptlang-detail">
        <img src="{{ get_obj.image.url }}" alt="" />
        <p>Added on: {{ get_obj.date_added }}</p>
        <p>Type: {{ get_obj.get_type_display }}</p>
    </div>
    <a href="{% url 'firstapp' %}">Back to List</a>
{% endblock %}

DjangoProject/firstapp/templates/firstapp/firstapp.html
{% extends 'layout.html' %}

{% block title %} 
    First App Page using Jinja 
{% endblock %}

{% block content %}
    <h1>FIRST APP Page | DHRUV MAISURIA</h1>
    <div class ="grid grid-cols-5  gap-4 m-4">
    
        {% for scriptLang in scriptingLang %}
        <div class="bg-blue-950 p-5 rounded">
            <img class ="rounded shadow-lg" src="{{ scriptLang.image.url }}" alt="" />
            <h3 class="text-2xl font-bold">{{ scriptLang.name }}</h3>
            <a href="{% url 'detail' scriptLang.id %}">
                
                <button type="button" class="inline-flex items-center w-[100%] justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus: ring-orange-500">
                    {{scriptLang.type}}- {{scriptingLang.id}}
        </div>
    {% endfor %}
{% endblock %}

DjangoProject/firstapp/templates/firstapp/order.html
{% extends 'layout.html' %}

{% block title %} 
    First App Page using Jinja 
{% endblock %}

{% block content %}
    <h1>FIRST APP Page | DHRUV MAISURIA</h1>
    <div class ="grid grid-cols-5  gap-4 m-4">
    
        {% for scriptLang in scriptingLang %}
        <div class="bg-purple-950 p-5 rounded">
            <img class ="rounded shadow-lg" src="{{ scriptLang.image.url }}" alt="" />
            <h3 class="text-2xl font-bold">{{ scriptLang.name }}</h3>
            <a href="{% url 'detail' scriptLang.id %}">
                <button type="button" class="inline-flex items-center w-[100%] justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus: ring-orange-500">
                    {{scriptLang.type}}- {{scriptingLang.id}}
        </div>
    {% endfor %}
{% endblock %}

DjangoProject/firstapp/templates/firstapp/script_stores.html
{% extends "layout.html" %}

{% block content %}
test content for forms
<form method ="POST" class="text-black">
    {% csrf_token %}
    {{form.as_p}}
    <button type ="submit">Search Store</button>
</form>

{% if stores %}
    <h2> Stores Available</h2>
    <ul>
        {% for store in stores %}
            <li> {{store.name}} - {{store.location}}</li>
        {% endfor %}
    </ul>

{% endif %}
{% endblock %}

DjangoProject/templates/layout.html
{% load static %}
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        {% block title %} 
        default value 
        {% endblock %}
    </title>
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'style.css'%}" />
  </head>
  <body>
    <nav>This is our navbar</nav>
    {% block content %}  {% endblock %}
  </body>
</html>

DjangoProject/templates/website/about.html
{% load static%}
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Django Project</title>
    <link rel="stylesheet" href="{% static "style.css" %}">
  </head>
  <body>
<h1> My First Django Project.</h1>
<h2> Welcome to Conact Page.</h2>

</body>  
</html>

DjangoProject/templates/website/career.html
{% load static%}
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Django Project</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
<h1> My First Django Project.</h1>
<h2> Welcome to Career Page.</h2>

</body>  
</html>

DjangoProject/templates/website/contact.html
{% load static%}
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Django Project</title>
    <link rel="stylesheet" href="{% static "style.css" %}">
  </head>
  <body>
<h1> My First Django Project.</h1>
<h2> Welcome to Conact Page.</h2>

</body>  
</html>

DjangoProject/templates/website/index.html
{% extends 'layout.html' %}

{% block title %}
Home Page usign jinja
{% endblock %}


{% block content %}

<h1 class="bg-yellow-500 text-3xl">Welocme To My First Django Project | DHRUVKUMAR RAJENDRAKUMAR MAISURIA</h1>
<p class="text-center w-20 bg-orange-500 text-3xl">
    <li>DHRUV</li>
    <li>Rajendrakumar</li>
    <li>maisuria</li>
    <li>8128179069</li>
</p>
{% endblock %}

DjangoProject/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>